### ISSUE TITLE
Uncaught Error: Non-static method

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/MatomoConnector#2]
i cannot replicate 

but I do have an error in your Matomo plugin:
![image](https://user-images.githubusercontent.com/26339368/209822041-82d20325-23ab-48f0-8f9e-998206a6d261.png)

`
Fatal error: Uncaught Error: Non-static method Kanboard\Plugin\MatomoConnector\Plugin::getPluginVersion() cannot be called statically in /var/www/app/plugins/MatomoConnector/Template/config/settings.php:113 Stack trace: #0 /var/www/app/app/Core/Template.php(83): include() #1 /var/www/app/app/Helper/LayoutHelper.php(207): Kanboard\Core\Template->render() #2 /var/www/app/app/Helper/LayoutHelper.php(129): Kanboard\Helper\LayoutHelper->subLayout() #3 /var/www/app/plugins/MatomoConnector/Controller/MatomoConnectorController.php(26): Kanboard\Helper\LayoutHelper->config() #4 /var/www/app/app/Core/Controller/Runner.php(77): Kanboard\Plugin\MatomoConnector\Controller\MatomoConnectorController->show() #5 /var/www/app/app/Core/Controller/Runner.php(31): Kanboard\Core\Controller\Runner->executeController() #6 /var/www/app/index.php(9): Kanboard\Core\Controller\Runner->execute() #7 {main} thrown in /var/www/app/plugins/MatomoConnector/Template/config/settings.php on line 113
`

_Originally posted by @creecros in https://github.com/aljawaid/ColorManager/issues/18#issuecomment-1366665852_

**Comment by aljawaid** [comment]
Ok got it. 

**1st**
 You need to add this code to `show()` in your controller
`use Kanboard\Core\Plugin\Installer;`

```
public function show()
    {
        $this->response->html($this->helper->layout->config('matomoConnector:config/settings', array(
            'plugins' => $this->pluginLoader->getPlugins(),
            'title' => 'MatomoConnector &#10562; '.t('Settings'),
        )));
    }
```

Then in the settings template you can now use:
```
        <?php
        $pluginName = $this->app->getPluginName();
        $pluginVersion = $plugins[$pluginName]->getPluginVersion();
        $pluginHomepage = $plugins[$pluginName]->getPluginHomepage();
        ?>
```

![image](https://user-images.githubusercontent.com/26339368/209838069-1e2ed04c-ec04-43c7-b21e-b89bc268f1b4.png)

Originally posted by @creecros in  https://github.com/aljawaid/ColorManager/issues/18#issuecomment-1366748940
